services:
  - type: web
    name: hackrx-policy-qa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: HACKRX_API_KEY
        sync: false 